{
  config,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
  ];

  users.users.qt1 = {
    uid = 501;
    extraGroups = [
      "wheel"
      "orbstack"
    ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/qt1";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/Paris";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    resolvconf.enable = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
            -----BEGIN CERTIFICATE-----
      MIICDTCCAbKgAwIBAgIQWz1Sc0F+FCB6P+bW47i1PjAKBggqhkjOPQQDAjBmMR0w
      GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
      cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
      IENBMB4XDTI2MDQyMTE5NDUzOVoXDTM2MDQyMTE5NDUzOVowZjEdMBsGA1UEChMU
      T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
      aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
      ByqGSM49AgEGCCqGSM49AwEHA0IABCa5qnZ5lkCv12CEFCzdK5+5bsF5HJuQYfJy
      v/nHO69jq2JZLMCtLFJg1o7oHskqHBq6W25XIiXHBPcBN58qrR2jQjBAMA4GA1Ud
      DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQPaX9OlJII4F8X
      IZpYfYxze4bGmTAKBggqhkjOPQQDAgNJADBGAiEAwx5V7pq4IN9CIETeaFNsE8qI
      BRSSO1pdPTxx7QujJhMCIQDMZeKIRDo8vNXKe6oVnMHJwdoyg1G9uTvPMNjX9Yci
      PQ==
      -----END CERTIFICATE-----

    ''
  ];

  system.stateVersion = "26.05";
}
